# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('introduccion', models.TextField()),
                ('para_que', models.TextField()),
                ('como', models.TextField()),
            ],
        ),
    ]
