# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementosConsejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemnto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listado', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='consejo',
            name='como',
        ),
        migrations.RemoveField(
            model_name='consejo',
            name='para_que',
        ),
        migrations.AddField(
            model_name='listado',
            name='lista_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listado_de', to='guia.Consejo'),
        ),
        migrations.AddField(
            model_name='elementosconsejo',
            name='pertenece_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemento_de', to='guia.Listado'),
        ),
    ]
