# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_auto_20160604_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementosconsejo',
            old_name='elemnto',
            new_name='elemento',
        ),
    ]
