# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoListado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('introduccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listado', models.CharField(max_length=120)),
                ('lista_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listado_de', to='guia_tecnica.GuiaTecnica')),
            ],
        ),
        migrations.AddField(
            model_name='elementolistado',
            name='pertenece_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemento_de', to='guia_tecnica.Listado'),
        ),
    ]
