# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMonografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precioSemilla', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('regiones', models.TextField(max_length=500)),
                ('cuidados', models.TextField(max_length=500)),
            ],
        ),
    ]
